spring:
  application:
    name: shianxian-eureka
  #开启权限认证
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 123456

server:
  host: localhost
  port: 8092

# eureka
eurekaServer:
  host: localhost
  user: admin
  password: 123456
  # eureka端口1
  port1: 8091

eureka:
  client:
    service-url:
      # 开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
      # 两个eureka相互注册构建集群
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port1}/eureka

# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-dev.xml